BASE_DIR = ""
RESULT_DIR = BASE_DIR + "result/"
DATA_DIR = BASE_DIR + "data/"
BASE_PREPROCESSEDIMAGES_DIR = RESULT_DIR + "preprocessed_images/"
BASE_TRAIN_SEGMENT_DIR = RESULT_DIR + "segmenter_trainset/"
PATIENT_PRED_DIR = RESULT_DIR + "patient_predictions/"

MODEL_NAME = "vgg"
TRAIN_EPOCHS = 40
FOLD_COUNT = 6

TARGET_SIZE = 256
TARGET_CROP = 224
CROP_INDENT_X = 16
CROP_INDENT_Y = 16
CROP_SIZE = 16
