BASE_DIR = "../../"
RESULT_DIR = BASE_DIR + "result/"
DATA_DIR = BASE_DIR + "data/"
BASE_PREPROCESSEDIMAGES_DIR = RESULT_DIR + "/data_preprocessed_images/"
BASE_TRAIN_SEGMENT_DIR = RESULT_DIR + "/data_segmenter_trainset/"
PATIENT_PRED_DIR = RESULT_DIR + "/data_patient_predictions/"

MODEL_NAME = "vgg"
TRAIN_EPOCHS = 40
FOLD_COUNT = 6
TARGET_SIZE = 256
CROP_INDENT_X = 32
TARGET_CROP = 184
CROP_INDENT_Y = 32 - ((TARGET_CROP - 160) / 2)
CROP_SIZE = 16
